version: '3'
services:
  rest-service-a:
    image: spring-rest-service-a
#    ports:
#     - "8080:8080"
    depends_on:
     - eureka-server
  rest-service-c:
    image: spring-rest-service-b
#    ports:
#     - "9090:9090"
    depends_on:
     - rest-service-a

  eureka-server:
    image: spring-eureka-server
    ports:
     - "8761:8761"
